version: '3.7'
services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: 7.2.x-webserver-off
    ports:
      - '80:80'
      - '443:443'
    links:
      - mysql
    networks:
      - mmd-off-net
    volumes:
      - '${DOCUMENT_ROOT-./www}:/var/www/html'
      - '${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini'
      - '${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled'
      - '${LOG_DIR-./logs/apache2}:/var/log/apache2'
    environment:
      - PHP_IDE_CONFIG=serverName=DockerMemodoOffice
  mysql:
    build: ./bin/mysql
    container_name: 8.0.19-mysql-off
    command: '--default-authentication-plugin=mysql_native_password'
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE https://stackoverflow.com/a/55706057/3935401
    ports:
      - '3306:3306'
    networks:
      - mmd-off-net
    volumes:
      - '${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql'
      - '${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql'
      - './config/mysql/my.cnf:/etc/my.cnf'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
networks:
  mmd-off-net:
    name: mmd-off-global-net
